services:
  db:
    image: timescale/timescaledb-ha:pg15-latest
    command:
      - -cshared_preload_libraries=timescaledb,pg_cron
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=opensensemap
    ports:
      - 5432:5432